---
- hosts: web
  vars:
    db_password: password
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_key: QujjaJs3fxwtnTl7FiqhEEn1ACkf7YZW
    app_env: test
    db_host: localhost
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: change selinux mode to permissive
      become: yes
      lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=" line="SELINUX=permissive"
# **

    - name: Set permissive mode
      become: yes
      command: setenforce 0

    - name: Install EPEL repo
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Install packages
      become: yes
      yum: name=nginx,php,php-fpm,php-ldap,php-mbstring,php-mcrypt,php-mysql,php-phpunit-PHPUnit update_cache=yes state=present
      register: nginx_install

    - name: Install composer
      become: yes
      shell: get -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: Nginx configuration
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0644
      register: nginx_conf
#check config file 

#**
    - name: Change root pass
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

# Moved up from bw Check directory / Update composer (73, 77)
    - name: Unarchive web/curriculum
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: Move files from /web to /etc after unarchive
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: Move files from /web to /etc after unarchive
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: Restart nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

#**
    - name: Restart php
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: Check directory for file
      become: yes
      file: path="{{ service_dir }}" state=file

    - name: Update composer
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

    - name: Recurrsively sets permissions to all files
      become: yes
      command: chmod -R 0644 storage chdir="{{ service_dir }}"

# look up "."
    - name: Recurrsively sets owner to all files
      command: chown -R nginx:nginx . chdir="{{ service_dir }}"

    - name: Move env file to /.env
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx

